### ISSUE TITLE
8Mhz compatibility

### ISSUE THREAD

**Issue by Kwenchana** [ArminJo/LightweightServo#1]
I tested this librairy and I like how lightweight it is but it seems to only work at 16Mhz, I looked at Adafruit's TiCoServo and the initialization register appears similar but the write function does take into account the CPU clock speed and adjust the ticks accordingly

**Comment by ArminJo** [comment]
Thanks for reporting 🥇 
Can you please test the version and give feedback?
Then I can release it 😃 .

**Comment by Kwenchana** [comment]
woah thanks for the speedy fix, working beautifully, I'm using your librairy to convert a brushed motor h bridge forward/reverse signals into servo PWM :D
